version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: driveradda_postgres
    restart: always
    environment:
      POSTGRES_DB: driveradda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: driveradda_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/driveradda
      - SECRET_KEY=supersecretkeydriveradda12345!@#
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=DriverAdda2026!
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: driveradda_frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
